spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.116.213.241:3306/2018214201?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: 2018214201
    password: 2018214201
  jackson:
    default-property-inclusion: non_null
  # redis配置
  redis:
    host: 122.9.46.43
    password: zsq201017

# Mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.example.lab_reservation_system_backend_server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加密使用的密钥
  secret: lab-reservation
  # JWT的超期限时间(60 * 60 * 24 * 30)
  expiration: 18144000
  # JWT 负载中拿到开头
  tokenHead: Bearer

logging:
  level:
    root: warn
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
